version: '3'
services:
  redis:
    image: redis:5.0-alpine
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - /wangying/malldata/redis/data:/data   #数据文件挂载
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    container_name: rabbitmq
    volumes:
      - /wangying/malldata/rabbitmq/data:/var/lib/rabbitmq #数据文件挂载
      - /wangying/logs/rabbitmq/log:/var/log/rabbitmq #日志文件挂载
    ports:
      - 5672:5672
      - 15672:15672
  
  elasticsearch:
    image: elasticsearch:7.4.2
    container_name: elasticsearch
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #设置使用jvm内存大小
    volumes:
      - /wangying/malldata/elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - /wangying/malldata/elasticsearch/data:/usr/share/elasticsearch/data #数据文件挂载
    ports:
      - 9200:9200
  
  kibana:
    image: kibana:7.4.2
    container_name: kibana
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "elasticsearch.hosts=http://es:9200" #设置访问elasticsearch的地址
    ports:
      - 5601:5601